# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_out.ui'
#
# Created: Mon Feb 20 23:47:05 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogOut(object):
    def setupUi(self, DialogOut):
        DialogOut.setObjectName("DialogOut")
        DialogOut.resize(523, 440)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogOut.sizePolicy().hasHeightForWidth())
        DialogOut.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        DialogOut.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pics/pic.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogOut.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(DialogOut)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(-1, 13, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtGui.QLabel(DialogOut)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_name.setFont(font)
        self.label_name.setWordWrap(True)
        self.label_name.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_text = QtGui.QLabel(DialogOut)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_text.setFont(font)
        self.label_text.setTextFormat(QtCore.Qt.PlainText)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        self.horizontalLayout.addWidget(self.label_text)
        self.label_ip = QtGui.QLabel(DialogOut)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_ip.setFont(font)
        self.label_ip.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_ip.setObjectName("label_ip")
        self.horizontalLayout.addWidget(self.label_ip)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_domain = QtGui.QLabel(DialogOut)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_domain.setFont(font)
        self.label_domain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_domain.setObjectName("label_domain")
        self.horizontalLayout_2.addWidget(self.label_domain)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(DialogOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_allow = QtGui.QPushButton(self.groupBox)
        self.pushButton_allow.setObjectName("pushButton_allow")
        self.horizontalLayout_3.addWidget(self.pushButton_allow)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalFrame = QtGui.QFrame(self.groupBox)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_show = QtGui.QPushButton(self.verticalFrame)
        self.pushButton_show.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_show.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_show.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_show.setIconSize(QtCore.QSize(1, 16))
        self.pushButton_show.setAutoDefault(False)
        self.pushButton_show.setFlat(True)
        self.pushButton_show.setObjectName("pushButton_show")
        self.verticalLayout_3.addWidget(self.pushButton_show)
        self.pushButton_hide = QtGui.QPushButton(self.verticalFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton_hide.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_hide.setFont(font)
        self.pushButton_hide.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_hide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_hide.setAutoDefault(False)
        self.pushButton_hide.setFlat(True)
        self.pushButton_hide.setObjectName("pushButton_hide")
        self.verticalLayout_3.addWidget(self.pushButton_hide)
        self.horizontalLayout_3.addWidget(self.verticalFrame)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_deny = QtGui.QPushButton(self.groupBox)
        self.pushButton_deny.setObjectName("pushButton_deny")
        self.horizontalLayout_3.addWidget(self.pushButton_deny)
        self.verticalLayout.addWidget(self.groupBox)
        self.checkBox = QtGui.QCheckBox(DialogOut)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(DialogOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/pics/tux2.jpg"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(-1, -1, 13, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_details = QtGui.QTableWidget(DialogOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_details.sizePolicy().hasHeightForWidth())
        self.tableWidget_details.setSizePolicy(sizePolicy)
        self.tableWidget_details.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_details.setAutoFillBackground(False)
        self.tableWidget_details.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_details.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_details.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_details.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_details.setAlternatingRowColors(True)
        self.tableWidget_details.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_details.setCornerButtonEnabled(True)
        self.tableWidget_details.setRowCount(7)
        self.tableWidget_details.setColumnCount(2)
        self.tableWidget_details.setObjectName("tableWidget_details")
        self.tableWidget_details.setColumnCount(2)
        self.tableWidget_details.setRowCount(7)
        self.tableWidget_details.horizontalHeader().setVisible(False)
        self.tableWidget_details.horizontalHeader().setDefaultSectionSize(141)
        self.tableWidget_details.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_details.verticalHeader().setVisible(False)
        self.tableWidget_details.verticalHeader().setDefaultSectionSize(27)
        self.tableWidget_details.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableWidget_details)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.actionOop = QtGui.QAction(DialogOut)
        self.actionOop.setCheckable(True)
        self.actionOop.setObjectName("actionOop")

        self.retranslateUi(DialogOut)
        QtCore.QObject.connect(self.pushButton_show, QtCore.SIGNAL("clicked()"), self.pushButton_show.hide)
        QtCore.QObject.connect(self.pushButton_show, QtCore.SIGNAL("clicked()"), self.pushButton_hide.show)
        QtCore.QObject.connect(self.pushButton_hide, QtCore.SIGNAL("clicked()"), self.pushButton_hide.hide)
        QtCore.QObject.connect(self.pushButton_hide, QtCore.SIGNAL("clicked()"), self.pushButton_show.show)
        QtCore.QObject.connect(self.pushButton_hide, QtCore.SIGNAL("clicked()"), self.tableWidget_details.hide)
        QtCore.QObject.connect(self.pushButton_show, QtCore.SIGNAL("clicked()"), self.tableWidget_details.show)
        QtCore.QObject.connect(self.pushButton_allow, QtCore.SIGNAL("clicked()"), DialogOut.hide)
        QtCore.QObject.connect(self.pushButton_deny, QtCore.SIGNAL("clicked()"), DialogOut.hide)
        QtCore.QMetaObject.connectSlotsByName(DialogOut)
        DialogOut.setTabOrder(self.pushButton_allow, self.pushButton_deny)
        DialogOut.setTabOrder(self.pushButton_deny, self.checkBox)
        DialogOut.setTabOrder(self.checkBox, self.pushButton_show)
        DialogOut.setTabOrder(self.pushButton_show, self.pushButton_hide)

    def retranslateUi(self, DialogOut):
        DialogOut.setWindowTitle(QtGui.QApplication.translate("DialogOut", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_name.setText(QtGui.QApplication.translate("DialogOut", "Application name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_text.setText(QtGui.QApplication.translate("DialogOut", "is trying to connect to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip.setText(QtGui.QApplication.translate("DialogOut", "IP address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_domain.setText(QtGui.QApplication.translate("DialogOut", "Domain name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_allow.setText(QtGui.QApplication.translate("DialogOut", "&Allow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_show.setText(QtGui.QApplication.translate("DialogOut", "&Show details...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hide.setText(QtGui.QApplication.translate("DialogOut", "&Hide details...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deny.setText(QtGui.QApplication.translate("DialogOut", "&Deny", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("DialogOut", "&Remeber my choice for all future connection attempts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOop.setText(QtGui.QApplication.translate("DialogOut", "oop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOop.setToolTip(QtGui.QApplication.translate("DialogOut", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<table style=\"-qt-table-type: root; margin-top:4px; margin-bottom:4px; margin-left:4px; margin-right:4px;\">\n"
"<tr>\n"
"<td style=\"border: none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">klkllk<span style=\" font-weight:600;\">kkkkkk</span></p></td></tr></table></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
